- site: levante
  pool:
    fesom2:
      path: /pool/data/AWICM/FESOM2
      output: ~/checksum_fesom2_levante.csv
      ignore:
      - .git
  slurm:
    -A: ab0246
    -p: compute
    -t: '3:00:00'
  extras:
  - "module load python3/2023.01-gcc-11.2.0"
- site: albedo
  pool:
    fesom2:
      path: /albedo/pool/FESOM2
      output: ~/checksum_fesom2_albedo.csv
      ignore:
      - .git
  slurm:
    --mem: 100GB
    --qos: 12h
    -p: mpp
    -t: '3:00:00'
  extras:
  - "module load analysis-toolbox/03.2023"