#=======================================================================================
# LEVANTE (DKRZ)
#=======================================================================================
levante:
  pool:
    fesom2:
      path: /pool/data/AWICM/FESOM2
      outfile: ~/checksum_fesom2_levante.csv
      ignore:
      - .git
      - __pycache__
    fesom:
      path: /pool/data/AWICM/FESOM1
      outfile: ~/checksum_fesom1_levante.csv
      ignore:
      - .git
    echam:
      path: /pool/data/ECHAM6
      outfile: ~/checksum_echam_levante.csv
      ignore:
      - .git
    jsbach:
      path: /pool/data/JSBACH
      outfile: ~/checksum_jsbach_levante.csv
      ignore:
      - .git
  slurm:
    -A: ab0246
    -p: compute
    -t: '3:00:00'
  python_executable: /sw/spack-levante/mambaforge-22.9.0-2-Linux-x86_64-kptncg/bin/python
  host: a270243@levante.dkrz.de  # username@hostnamelevante:
  node_names:
    login: 'levante*'
    compute: '^l[A-Za-z0-9]+\.lvt\.dkrz.de$'

#=======================================================================================
# ALBEDO (AWI)
#=======================================================================================
albedo:
  pool:
    fesom2:
      path: /albedo/pool/FESOM2
      outfile: ~/checksum_fesom2_albedo.csv
      ignore:
      - .git
    echam:
      path: /albedo/pool/ECHAM6
      outfile: ~/checksum_echam_albedo.csv
      ignore:
      - .git
    jsbach:
      path: /albedo/pool/JSBACH
      outfile: ~/checksum_jsbach_albedo.csv
      ignore:
      - .git
  slurm:
    --mem: 100GB
    --qos: 12h
    -p: mpp
    -t: '3:00:00'
  python_executable: /albedo/soft/sw/spack-sw/python/3.10.4-daos5pe/bin/python
  # here host info is not used as connection to albedo from outside is not possible
  host: pasili001@albedo0.dmawi.de # username@hostname
  node_names:
    login:
        - 'albedo0'
        - 'albedo1'
    compute: 'prod-*'
    gpu: 'gpu-*'
    fat: 'fat-*'
    post: None

#=======================================================================================
# JUWELS (JSC)
#=======================================================================================
juwels:
  node_names:
    login: '^jwlogin[0-9][0-9]\.juwels'
    compute: '^jwc[0-9][0-9]*'

#=======================================================================================
# BLOGIN (HLRN)
#=======================================================================================
blogin:
  node_names:
    login: 'blogin*'
    compute: '^b[A-Za-z0-9]+\.usr\.hlrn\.de$'
    post: 'blogin*'

#=======================================================================================
# GLOGIN (HLRN)
#=======================================================================================
glogin:
  node_names:
    login: 'glogin*'
    compute: '^g[A-Za-z0-9]+\.usr\.hlrn\.de$'
    post: 'glogin*'

#=======================================================================================
# ALEPH (ICCP)
#=======================================================================================
aleph:
  node_names:
    login: 'elogin*'
    compute: 'mom*'
    post: 'elogin*'

#=======================================================================================
# NESH (CAU)
#=======================================================================================
nesh:
  node_names:
    login: 'nesh*'
    compute:
        - 'neshcl*'
        - 'nesh-bigmem*'
    post: 'neshcl*'
