name: Bug Report
description: Report a bug in ptool
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to report a bug!"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behaviour.
      placeholder: |
        1. Run `ptool checksums ...`
        2. Then run `ptool compare ...`
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Output of `ptool --version` and `python --version`.
    validations:
      required: true
